apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jenkins-x
    provider: github
    repository: jx-cli
  name: jenkins-x-jx-cli
spec:
  httpCloneURL: https://github.com/jenkins-x/jx-cli.git
  org: jenkins-x
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx-cli
  scheduler:
    kind: ""
    name: cheese
  url: https://github.com/jenkins-x/jx-cli
